language: php

php:
 - 7.0

env:
  matrix:
    - PREFER_LOWEST="--prefer-lowest"
    - PREFER_LOWEST=""

before_script:
 - composer update --no-interaction --prefer-source $PREFER_LOWEST

script:
 - phpunit

after_script:
 - php vendor/bin/coveralls -v
